---
id: hatohol-log-monitoring-2014-10
base_name: overview
tags:
- rabbit
- hatohol
presentation_date: 2014-10-7
version: 2014.10.7.0
licenses:
- CC0-1.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: 
  speaker_deck_user: 
